import { saveManager } from './saveManager.js';
class AudioManager{
  constructor(){ this.ctx=null; this.music=null; this.last={}; this.musicKey=''; }
  unlockAudio(){ try{ this.ctx??=new (window.AudioContext||window.webkitAudioContext)(); if(this.ctx.state==='suspended')this.ctx.resume(); }catch{} }
  tone(freq=440,duration=.08,type='sine',volume=.12,delay=0){ if(!this.ctx||this.ctx.state!=='running')return; const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain(); o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(volume*saveManager.data.sfxVolume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+duration); }
  playSfx(key){ const now=performance.now(); if(now-(this.last[key]||0)<45)return;this.last[key]=now; const m={hover:[440,.04,'sine'],click:[700,.06,'square'],swing:[210,.08,'sawtooth'],hit:[95,.1,'square'],heavy:[70,.16,'sawtooth'],hurt:[120,.18,'square'],dash:[330,.12,'triangle'],pickup:[600,.1,'sine'],drop:[270,.08,'triangle'],throw:[180,.12,'sawtooth'],explosion:[55,.35,'sawtooth'],emp:[90,.45,'square'],laser:[860,.16,'sawtooth'],door:[140,.35,'triangle'],puzzle:[740,.3,'sine'],heal:[520,.25,'sine'],log:[460,.3,'triangle'],upgrade:[880,.35,'sine'],warning:[190,.25,'square'],achievement:[980,.4,'sine'],boss:[48,.7,'sawtooth'],phase:[75,.6,'square'],gameover:[65,.9,'triangle'],victory:[620,.8,'sine'],record:[1100,.7,'sine']}; const p=m[key]||[300,.08,'sine'];this.tone(...p); if(['puzzle','upgrade','victory','record'].includes(key))this.tone(p[0]*1.5,p[1],p[2],.1,.1); }
  playMusic(key){ this.unlockAudio(); if(this.musicKey===key)return;this.stopMusic();this.musicKey=key;if(!this.ctx)return; const patterns={menu:[110,165,220],stage:[82,123,164,123],boss:[65,98,130,196]};let i=0;this.music=setInterval(()=>{const f=patterns[key]?.[i++%(patterns[key]?.length||1)]||110;this.toneMusic(f);},key==='boss'?220:520); }
  toneMusic(freq){ if(!this.ctx||this.ctx.state!=='running')return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.045*saveManager.data.bgmVolume,t);g.gain.exponentialRampToValueAtTime(.0001,t+.4);o.connect(g).connect(this.ctx.destination);o.start();o.stop(t+.42); }
  stopMusic(){ if(this.music)clearInterval(this.music);this.music=null;this.musicKey=''; }
  setBgmVolume(v){saveManager.set('bgmVolume',v);} setSfxVolume(v){saveManager.set('sfxVolume',v);}
}
export const audioManager=new AudioManager();
