import { WIDTH, HEIGHT, COLORS, DIFFICULTIES, SCORE, PROFILE_LABELS } from '../config.js';
import { gameSession } from '../gameSession.js';
import { Player } from '../entities/Player.js';
import { ThrowableObject } from '../entities/ThrowableObject.js';
import { Drone } from '../entities/Drone.js';
import { GuardRobot } from '../entities/GuardRobot.js';
import { Turret } from '../entities/Turret.js';
import { Charger } from '../entities/Charger.js';
import { EffectsManager } from '../effectsManager.js';
import { audioManager } from '../audioManager.js';
import { scoreManager } from '../scoreManager.js';
import { achievementManager } from '../achievementManager.js';
import { analyzeProfile, adaptiveModifiers } from '../adaptiveAI.js';
export class BaseGameScene extends Phaser.Scene{
  constructor(key){super(key);this.stageKey=key;}
  createCommon(stageTitle,worldWidth=2200,worldHeight=900,start={x:120,y:450}){
    this.enemySerial=1;this.transitioning=false;this.inputLocked=true;this.logOpen=false;this.stageEnded=false;this.combatActive=false;this.lastCombatAction=0;this.profile=gameSession.temporaryProfile||'balanced';this.effects=new EffectsManager(this);this.walls=this.physics.add.staticGroup();this.enemies=this.physics.add.group();this.throwables=this.physics.add.group();this.projectiles=this.physics.add.group();this.tempObjects=[];this.stageTimers=[];
    gameSession.setStage(this.stageKey);this.physics.world.setBounds(0,0,worldWidth,worldHeight);this.cameras.main.setBounds(0,0,worldWidth,worldHeight).setBackgroundColor(COLORS.bg);this.drawFacility(worldWidth,worldHeight);this.buildBoundary(worldWidth,worldHeight);this.player=new Player(this,start.x,start.y);this.cameras.main.startFollow(this.player,true,.09,.09);this.cameras.main.setDeadzone(170,120);this.physics.add.collider(this.player,this.walls);this.physics.add.collider(this.enemies,this.walls,(e)=>e.onWallHit?.());this.physics.add.collider(this.throwables,this.walls,(o)=>{if(o.type==='barrel'&&o.thrown)o.explode();else if(o.body){o.body.setVelocity(o.body.velocity.x*-.15,o.body.velocity.y*-.15);o.thrown=false;}});this.physics.add.overlap(this.throwables,this.enemies,(o,e)=>o.impact(e));this.physics.add.overlap(this.player,this.projectiles,(p,b)=>{if(!b.active)return;p.takeDamage(b.damage,b);b.destroy();});this.physics.add.collider(this.projectiles,this.walls,b=>b.destroy());
    this.setupInputs();this.createHUD(stageTitle);audioManager.playMusic(this.stageKey==='BossScene'?'boss':'stage');this.time.delayedCall(900,()=>{this.inputLocked=false;this.objectiveText.setAlpha(1);});this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.cleanup());this.game.events.on(Phaser.Core.Events.BLUR,this.onFocusLost,this);this.time.delayedCall(50,()=>gameSession.saveCheckpoint());
  }
  drawFacility(w,h){const g=this.add.graphics().setDepth(-20);g.fillStyle(COLORS.floor).fillRect(0,0,w,h);g.lineStyle(1,COLORS.cyan,.09);for(let x=0;x<w;x+=80)g.lineBetween(x,0,x,h);for(let y=0;y<h;y+=80)g.lineBetween(0,y,w,y);for(let x=120;x<w;x+=420){g.fillStyle(COLORS.panel,.7).fillRoundedRect(x,90,180,58,8);g.lineStyle(2,COLORS.cyan,.25).strokeRoundedRect(x,90,180,58,8);g.fillStyle(COLORS.red,.65).fillCircle(x+25,119,7);}}
  buildBoundary(w,h){this.addWall(w/2,22,w,44);this.addWall(w/2,h-22,w,44);this.addWall(22,h/2,44,h);this.addWall(w-22,h/2,44,h);}
  addWall(x,y,w,h,color=0x102735){const r=this.add.rectangle(x,y,w,h,color).setStrokeStyle(2,0x315465).setDepth(5);this.physics.add.existing(r,true);this.walls.add(r);return r;}
  addDoor(x,y,w=36,h=190){const d=this.add.rectangle(x,y,w,h,0x38131c).setStrokeStyle(3,COLORS.red).setDepth(6);this.physics.add.existing(d,true);this.walls.add(d);d.open=()=>{audioManager.playSfx('door');this.tweens.add({targets:d,alpha:0,duration:500,onComplete:()=>d.destroy()});};return d;}
  spawn(type,x,y,mods=null){const m=mods||adaptiveModifiers(this.stageKey==='ServerScene'?this.profile:'balanced',gameSession.difficulty);return ({drone:Drone,guard:GuardRobot,turret:Turret,charger:Charger}[type]);}
  createEnemy(type,x,y,mods=null){const C=this.spawn(type,x,y,mods);return new C(this,x,y,mods||adaptiveModifiers(this.stageKey==='ServerScene'?this.profile:'balanced',gameSession.difficulty));}
  createThrowable(type,x,y,options={}){const o=new ThrowableObject(this,x,y,type,options);this.throwables.add(o);return o;}
  createEnemyProjectile(x,y,tx,ty,damage,speed){if(this.projectiles.countActive(true)>=30)return;const b=this.physics.add.image(x,y,'enemyProjectile').setDepth(11);b.damage=damage;const a=Phaser.Math.Angle.Between(x,y,tx,ty);b.setVelocity(Math.cos(a)*speed,Math.sin(a)*speed);this.projectiles.add(b);this.time.delayedCall(4000,()=>b?.active&&b.destroy());audioManager.playSfx('laser');}
  meleeEnemyHit(enemy,range,damage){if(Phaser.Math.Distance.Between(enemy.x,enemy.y,this.player.x,this.player.y)<=range)this.player.takeDamage(damage,enemy);}
  setupInputs(){this.keys=this.input.keyboard.addKeys({up:'W',down:'S',left:'A',right:'D',up2:'UP',down2:'DOWN',left2:'LEFT',right2:'RIGHT',attack:'J',dash:'SHIFT',carry:'F',throw:'K',emp:'Q',interact:'E',pause:'ESC'});const bind=(key,fn)=>{const cb=()=>{if(!this.inputLocked&&!this.transitioning&&!this.logOpen)fn();};key.on('down',cb);this.inputBindings??=[];this.inputBindings.push([key,cb]);};bind(this.keys.attack,()=>this.player.attack());bind(this.keys.dash,()=>this.player.dash());bind(this.keys.carry,()=>this.player.toggleCarry());bind(this.keys.throw,()=>this.player.throwObject());bind(this.keys.emp,()=>this.player.useEmp());bind(this.keys.interact,()=>this.onInteract());this.pauseHandler=()=>{if(this.logOpen){this.closeLog();return;}this.openPause();};this.keys.pause.on('down',this.pauseHandler);this.pointerHandler=p=>{if(this.inputLocked||this.transitioning||this.logOpen)return;if(p.rightButtonDown())this.player.throwObject(this.player.directionToPointer());else if(p.leftButtonDown())this.player.attack(this.player.directionToPointer());};this.input.on('pointerdown',this.pointerHandler);}
  createHUD(stageTitle){this.hud=this.add.container(0,0).setScrollFactor(0).setDepth(100);const panel=this.add.rectangle(15,14,470,142,0x020810,.86).setOrigin(0).setStrokeStyle(2,COLORS.cyan,.45),right=this.add.rectangle(WIDTH-425,14,410,142,0x020810,.86).setOrigin(0).setStrokeStyle(2,COLORS.cyan,.45);this.healthBar=this.add.rectangle(38,48,330,20,COLORS.red).setOrigin(0,.5);this.empBar=this.add.rectangle(38,88,0,14,COLORS.cyan).setOrigin(0,.5);this.statusText=this.add.text(38,25,'',{fontFamily:'monospace',fontSize:'17px',color:'#ffffff'});this.scoreText=this.add.text(38,108,'',{fontFamily:'monospace',fontSize:'18px',color:'#ffdc77'});this.stageText=this.add.text(WIDTH-405,30,stageTitle,{fontFamily:'monospace',fontSize:'20px',fontStyle:'bold',color:'#78fff0'});this.objectiveText=this.add.text(WIDTH-405,66,'목표 초기화 중...', {fontFamily:'monospace',fontSize:'17px',color:'#ffffff',wordWrap:{width:380}});this.timeText=this.add.text(WIDTH-405,122,'',{fontFamily:'monospace',fontSize:'16px',color:'#a8bbc0'});this.bottomText=this.add.text(25,HEIGHT-32,'',{fontFamily:'monospace',fontSize:'16px',color:'#dffffa'});this.hud.add([panel,right,this.healthBar,this.empBar,this.statusText,this.scoreText,this.stageText,this.objectiveText,this.timeText,this.bottomText]);}
  setObjective(text){this.objective=text;this.objectiveText?.setText(`현재 목표: ${text}`).setColor('#ffffff');this.tweens.add({targets:this.objectiveText,alpha:.2,duration:120,yoyo:true,repeat:2});}
  updateHUD(){const hp=gameSession.health/gameSession.maxHealth;this.healthBar.width=330*Math.max(0,hp);this.empBar.width=330*(gameSession.empGauge||0)/100;this.statusText.setText(`HP ${Math.ceil(gameSession.health)} / ${gameSession.maxHealth}    EMP ${Math.floor(gameSession.empGauge||0)}%`);this.scoreText.setText(`SCORE ${gameSession.score.toLocaleString()}   COMBO x${gameSession.currentCombo}`);const t=Math.floor(gameSession.playTime);this.timeText.setText(`${String(t/60|0).padStart(2,'0')}:${String(t%60).padStart(2,'0')}  ·  ${gameSession.difficulty}`);const profile=this.stageKey==='BossScene'?gameSession.finalProfile:(this.stageKey==='ServerScene'?gameSession.temporaryProfile:'COLLECTING DATA');this.bottomText.setText(`${this.player?.carried?`운반: ${this.player.carried.config.name}`:'F 집기'}  ·  DASH ${this.time.now>=this.player?.nextDash?'READY':'COOLDOWN'}  ·  NEXUS ANALYSIS: ${PROFILE_LABELS[profile]||profile.toUpperCase?.()||'BALANCED'}`);}
  update(time,delta){if(!this.player||this.logOpen||this.inputLocked||this.transitioning)return;const movement={left:{isDown:this.keys.left.isDown||this.keys.left2.isDown},right:{isDown:this.keys.right.isDown||this.keys.right2.isDown},up:{isDown:this.keys.up.isDown||this.keys.up2.isDown},down:{isDown:this.keys.down.isDown||this.keys.down2.isDown}};this.player.move(movement);this.enemies.getChildren().forEach(e=>e.update(time,delta));this.throwables.getChildren().forEach(o=>o.update(time,delta));gameSession.playTime+=delta/1000;scoreManager.update();if(this.enemies.getChildren().some(e=>e.isAlive)){gameSession.ai.combatTime+=delta/1000;if(this.player.body.speed<5&&this.player.state!=='Dash')gameSession.ai.standingStillTime+=delta/1000;}this.updateHUD();this.updateStage?.(time,delta);}
  onAccurateThrow(obj,target){gameSession.addEmp(3);if(gameSession.throwHitScoreCount<20){gameSession.throwHitScoreCount++;scoreManager.award('throw-hit',SCORE.throwHit,`throw-${obj.puzzleId||obj.spawnPoint.x}-${target.id}-${gameSession.throwHitScoreCount}`,true);}scoreManager.hit();}
  explodeBarrel(barrel){this.effects.ring(barrel.x,barrel.y,120,COLORS.red,280);this.effects.burst(barrel.x,barrel.y,COLORS.red,18);this.effects.shake(120,.005);this.enemies.getChildren().forEach(e=>{if(e.isAlive&&Phaser.Math.Distance.Between(barrel.x,barrel.y,e.x,e.y)<=120)e.takeDamage(55*gameSession.stats.throwDamageMultiplier,barrel,'throw');});if(Phaser.Math.Distance.Between(barrel.x,barrel.y,this.player.x,this.player.y)<=120)this.player.takeDamage(27.5,barrel);this.onBarrelExploded?.(barrel);}
  collectLog(id,title,body){const fresh=gameSession.collectLog(id);if(fresh){scoreManager.award('log',SCORE.log,`log-${id}`,false);audioManager.playSfx('log');}this.showLog(title,body);}
  showLog(title,body){if(this.logOpen)return;this.logOpen=true;this.physics.pause();const shade=this.add.rectangle(WIDTH/2,HEIGHT/2,WIDTH,HEIGHT,0x000000,.78).setScrollFactor(0).setDepth(200).setInteractive(),card=this.add.rectangle(WIDTH/2,HEIGHT/2,780,430,0x071722).setStrokeStyle(3,COLORS.cyan).setScrollFactor(0).setDepth(201),text=this.add.text(WIDTH/2,HEIGHT/2-30,`${title}\n\n${body}\n\n[E / Esc] 닫기`,{fontFamily:'monospace',fontSize:'23px',color:'#eaffff',align:'center',lineSpacing:11,wordWrap:{width:680}}).setOrigin(.5).setScrollFactor(0).setDepth(202);this.logUi=[shade,card,text];this.logCloseE=()=>this.closeLog();this.keys.interact.once('down',this.logCloseE);}
  closeLog(){if(!this.logOpen)return;this.logOpen=false;this.logUi?.forEach(o=>o.destroy());this.logUi=null;this.physics.resume();this.player.body.setVelocity(0);}
  showBroadcast(message,done){this.inputLocked=true;audioManager.playSfx('warning');const box=this.add.rectangle(WIDTH/2,190,900,120,0x16030a,.94).setStrokeStyle(4,COLORS.red).setScrollFactor(0).setDepth(210),text=this.add.text(WIDTH/2,190,`NEXUS ANALYSIS\n${message}`,{fontFamily:'monospace',fontSize:'22px',color:'#ffb5c1',align:'center'}).setOrigin(.5).setScrollFactor(0).setDepth(211);this.time.delayedCall(2700,()=>{box.destroy();text.destroy();done?.();});}
  finishStage(nextScene){if(this.stageEnded)return;this.stageEnded=true;this.transitioning=true;this.player.body.setVelocity(0);if(gameSession.stats.selfRepair)gameSession.health=Math.min(gameSession.maxHealth,gameSession.health+20);let message='행동 데이터 수집을 시작합니다.';if(this.stageKey==='SecurityScene'){gameSession.temporaryProfile=analyzeProfile(gameSession.ai);message=`${PROFILE_LABELS[gameSession.temporaryProfile]} 성향을 확인했습니다.\n대응 프로토콜을 적용합니다.`;}if(this.stageKey==='ServerScene'){gameSession.finalProfile=analyzeProfile(gameSession.ai);message=`최종 ${PROFILE_LABELS[gameSession.finalProfile]} 성향을 확정했습니다.`;}this.showBroadcast(message,()=>this.scene.start('UpgradeScene',{nextScene}));}
  playerDied(){if(this.transitioning)return;this.transitioning=true;gameSession.deathCount++;audioManager.playSfx('gameover');this.projectiles.clear(true,true);this.time.delayedCall(250,()=>this.scene.start('GameOverScene',{stage:this.stageKey}));}
  openPause(){if(this.scene.isActive('PauseScene')||this.transitioning)return;this.player.body.setVelocity(0);this.scene.pause();this.scene.launch('PauseScene',{pausedSceneKey:this.stageKey});}
  onFocusLost(){if(this.scene.isActive()&&!this.scene.isPaused()&&!this.logOpen&&!this.transitioning)this.openPause();}
  cleanup(){this.game.events.off(Phaser.Core.Events.BLUR,this.onFocusLost,this);this.input?.off('pointerdown',this.pointerHandler);this.inputBindings?.forEach(([k,cb])=>k.off('down',cb));this.keys?.pause?.off('down',this.pauseHandler);this.projectiles?.clear(true,true);this.effects?.clear();}
}
