import { BaseGameScene } from './BaseGameScene.js';
import { NexusBoss } from '../entities/NexusBoss.js';
import { gameSession } from '../gameSession.js';
import { COLORS, DIFFICULTIES, PROFILE_LABELS } from '../config.js';
import { audioManager } from '../audioManager.js';
export class BossScene extends BaseGameScene{
  constructor(){super('BossScene');}
  create(){
    this.createCommon('FINAL · NEXUS CORE',1500,900,{x:150,y:450});
    this.profile=['melee','throw','dodge','emp','defensive','balanced'].includes(gameSession.finalProfile)?gameSession.finalProfile:'balanced';
    this.boss=new NexusBoss(this,750,450);
    this.physics.add.overlap(this.throwables,this.boss,(o,b)=>o.impact(b));
    this.crateSpawns=[{x:160,y:160},{x:1340,y:160},{x:1340,y:740}];
    this.crates=this.crateSpawns.map((p,i)=>this.createThrowable('crate',p.x,p.y,{puzzleId:`boss-crate-${i}`}));
    this.createBossHud();this.inputLocked=true;this.boss.state='Intro';this.setObjective('NEXUS CORE를 파괴하십시오.');audioManager.stopMusic();
    this.showBossIntro();this.time.delayedCall(5200,()=>{if(!this.boss.isAlive)return;this.inputLocked=false;this.boss.isInvulnerable=false;this.boss.state='Phase1';audioManager.playMusic('boss');this.scheduleBossAttack(700);gameSession.saveCheckpoint();});
  }
  showBossIntro(){const shade=this.add.rectangle(640,360,1280,720,0x000000,.68).setScrollFactor(0).setDepth(190),text=this.add.text(640,350,'SUBJECT 042.\n\n행동 분석이 완료되었습니다.\n탈출 프로토콜을 종료합니다.\n\nNEXUS CORE',{fontFamily:'monospace',fontSize:'30px',fontStyle:'bold',color:'#ff9cad',align:'center',lineSpacing:10}).setOrigin(.5).setScrollFactor(0).setDepth(191);this.tweens.add({targets:this.boss.ring1,angle:720,duration:5000});this.tweens.add({targets:this.boss.ring2,angle:-540,duration:5000});audioManager.playSfx('boss');this.time.delayedCall(4600,()=>{shade.destroy();text.destroy();});}
  createBossHud(){this.bossHud=this.add.container(0,0).setScrollFactor(0).setDepth(130);this.bossBarBg=this.add.rectangle(340,175,600,24,0x15050a).setOrigin(0).setStrokeStyle(2,0xffffff,.5);this.bossBar=this.add.rectangle(344,179,592,16,COLORS.red).setOrigin(0);this.bossLabel=this.add.text(640,160,'NEXUS CORE · PHASE 1',{fontFamily:'monospace',fontSize:'20px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5);this.bossHud.add([this.bossBarBg,this.bossBar,this.bossLabel]);}
  update(time,delta){super.update(time,delta);this.boss?.update(time);if(this.boss?.isAlive){this.bossBar.width=592*Math.max(0,this.boss.health/this.boss.maxHealth);this.bossLabel.setText(`NEXUS CORE · PHASE ${this.boss.phase} · ${Math.ceil(this.boss.health)} / ${Math.ceil(this.boss.maxHealth)}`);this.ensureCrates();}}
  ensureCrates(){this.crateSpawns.forEach((p,i)=>{const exists=this.throwables.getChildren().some(o=>o.active&&o.puzzleId===`boss-crate-${i}`);if(!exists&&!this.crateTimers?.[i]){this.crateTimers??=[];this.crateTimers[i]=this.time.delayedCall(8000,()=>{this.crateTimers[i]=null;if(this.boss.isAlive&&!this.throwables.getChildren().some(o=>o.active&&o.puzzleId===`boss-crate-${i}`))this.createThrowable('crate',p.x,p.y,{puzzleId:`boss-crate-${i}`});});}});}
  scheduleBossAttack(delay){this.bossAttackTimer?.remove(false);this.bossAttackTimer=this.time.delayedCall(delay,()=>this.runBossAttack());}
  runBossAttack(){if(!this.boss?.isAlive||this.boss.isInvulnerable||this.boss.isTransitioningPhase||this.boss.state==='Disabled'){this.scheduleBossAttack(350);return;}const base=['laser','radial','hazard','summon'],choices=base.filter(x=>x!==this.boss.lastAttack);if(this.boss.phase===3)choices.push('rotating');if(this.boss.phase>=2&&this.profile!=='balanced')choices.push('adaptive');const type=Phaser.Utils.Array.GetRandom(choices);this.boss.lastAttack=type;this.boss.isAttackRunning=true;this.boss.attackCount++;({laser:()=>this.attackLaser(),radial:()=>this.attackRadial(),hazard:()=>this.attackHazard(false),summon:()=>this.attackSummon(),rotating:()=>this.attackRotating(),adaptive:()=>this.attackAdaptive()}[type])();}
  finishAttack(extra=0){if(!this.boss?.isAlive)return;this.boss.isAttackRunning=false;if(this.boss.phase===3&&this.boss.attackCount>=4){this.boss.attackCount=0;this.boss.state='Overheated';this.boss.core.setFillStyle(0xffd37a);this.time.delayedCall(1500,()=>{if(this.boss.isAlive){this.boss.state='Phase3';this.boss.core.setFillStyle(0x1a0611);this.scheduleBossAttack(500);}});return;}const gap=({Easy:1600,Normal:1400,Hard:1250}[gameSession.difficulty])*(this.boss.phase===1?1:this.boss.phase===2?.88:.76);this.scheduleBossAttack(gap+extra);}
  attackLaser(){const p=this.player,a=Phaser.Math.Angle.Between(this.boss.x,this.boss.y,p.x,p.y),length=900,g=this.add.rectangle(this.boss.x,this.boss.y,length,9,COLORS.red,.25).setOrigin(0,.5).setRotation(a).setDepth(6);audioManager.playSfx('warning');this.time.delayedCall(800*DIFFICULTIES[gameSession.difficulty].warning,()=>{if(!this.boss.isAlive){g.destroy();return;}g.setFillStyle(0xffffff,.92).setDisplaySize(length,22);audioManager.playSfx('laser');const dist=Phaser.Math.Distance.BetweenPoints(this.player,new Phaser.Math.Vector2(this.boss.x+Math.cos(a)*length,this.boss.y+Math.sin(a)*length));const line=new Phaser.Geom.Line(this.boss.x,this.boss.y,this.boss.x+Math.cos(a)*length,this.boss.y+Math.sin(a)*length);if(Phaser.Geom.Intersects.GetLineToCircle(line,new Phaser.Geom.Circle(this.player.x,this.player.y,24)).length)this.player.takeDamage(18*this.boss.attackDamageMultiplier,this.boss);this.time.delayedCall(450,()=>{g.destroy();this.finishAttack();});});}
  attackRadial(){const count={Easy:8,Normal:10,Hard:12}[gameSession.difficulty];audioManager.playSfx('warning');this.time.delayedCall(450,()=>{for(let i=0;i<count;i++){const a=i*Math.PI*2/count;this.createEnemyProjectile(this.boss.x,this.boss.y,this.boss.x+Math.cos(a)*200,this.boss.y+Math.sin(a)*200,10*this.boss.attackDamageMultiplier,260);}this.finishAttack();});}
  attackHazard(predicted=false){const p=this.player,lead=predicted?Math.min(.22,this.profile==='dodge'?.18:0):0,x=Phaser.Math.Clamp(p.x+p.body.velocity.x*lead,100,1400),y=Phaser.Math.Clamp(p.y+p.body.velocity.y*lead,100,800),r=70;this.effects.warningCircle(x,y,r,850);audioManager.playSfx('warning');this.time.delayedCall(predicted?800:900,()=>{if(this.boss.isAlive&&Phaser.Math.Distance.Between(x,y,p.x,p.y)<r)p.takeDamage((predicted?17:16)*this.boss.attackDamageMultiplier,{x,y});this.effects.burst(x,y,COLORS.red,14);this.finishAttack();});}
  attackSummon(){const alive=this.enemies.getChildren().filter(e=>e.isAlive).length;if(alive<2){this.createEnemy('drone',this.boss.x-180,this.boss.y-180);if(alive===0)this.createEnemy('drone',this.boss.x+180,this.boss.y+180);}this.finishAttack();}
  attackAdaptive(){if(this.profile==='melee'&&Phaser.Math.Distance.Between(this.player.x,this.player.y,this.boss.x,this.boss.y)<190){this.effects.warningCircle(this.boss.x,this.boss.y,155,650);this.time.delayedCall(650,()=>{if(Phaser.Math.Distance.Between(this.player.x,this.player.y,this.boss.x,this.boss.y)<155)this.player.takeDamage(20*this.boss.attackDamageMultiplier,this.boss);this.finishAttack(700);});return;}if(this.profile==='throw'){this.bossShieldActive=true;this.boss.ring2.setStrokeStyle(12,COLORS.purple);this.time.delayedCall(4000,()=>{this.bossShieldActive=false;this.boss.ring2.setStrokeStyle(7,COLORS.cyan);});this.finishAttack();return;}if(this.profile==='dodge'){this.attackHazard(true);return;}if(this.profile==='emp'){this.effects.ring(this.boss.x,this.boss.y,150,COLORS.purple,500);this.finishAttack();return;}if(this.profile==='defensive'){if(this.player.body.speed<5)this.attackHazard(false);else this.attackLaser();return;}this.attackHazard(false);}
  attackRotating(){const g=this.add.rectangle(this.boss.x,this.boss.y,700,16,0xff365f,.85).setOrigin(0,.5).setDepth(9),start=this.time.now,duration=3000,hitAt=0;audioManager.playSfx('warning');const ev=this.time.addEvent({delay:50,loop:true,callback:()=>{if(!g.active||!this.boss.isAlive){ev.remove();return;}const progress=(this.time.now-start)/duration,a=progress*Math.PI*1.5;g.setRotation(a);const line=new Phaser.Geom.Line(this.boss.x,this.boss.y,this.boss.x+Math.cos(a)*700,this.boss.y+Math.sin(a)*700);if(this.time.now>hitAt&&Phaser.Geom.Intersects.GetLineToCircle(line,new Phaser.Geom.Circle(this.player.x,this.player.y,24)).length){this.player.takeDamage(18*this.boss.attackDamageMultiplier,this.boss);hitAt=this.time.now+700;}if(progress>=1){ev.remove();g.destroy();this.finishAttack();}}});this.tempObjects.push(g);}
  transitionBossPhase(phase){if(this.boss.isTransitioningPhase||!this.boss.isAlive)return;this.boss.isTransitioningPhase=true;this.boss.isInvulnerable=true;this.cancelBossAttack();if(phase===2)this.boss.hasEnteredPhase2=true;else this.boss.hasEnteredPhase3=true;this.boss.phase=phase;this.boss.state='PhaseTransition';audioManager.playSfx('phase');this.effects.shake(180,.006);const message=phase===2?`${PROFILE_LABELS[this.profile]} 대응 장치를 활성화합니다.`:'ERROR. 예측 모델 손상. 통제 범위를 초과했습니다.';this.showBroadcast(message,()=>{});this.time.delayedCall(2200,()=>{if(!this.boss.isAlive)return;this.boss.isTransitioningPhase=false;this.boss.isInvulnerable=false;this.boss.state=`Phase${phase}`;if(phase===2&&this.boss.health/this.boss.maxHealth<=.3&&!this.boss.hasEnteredPhase3)this.transitionBossPhase(3);else this.scheduleBossAttack(500);});}
  cancelBossAttack(){this.bossAttackTimer?.remove(false);this.tempObjects.forEach(o=>o?.destroy?.());this.tempObjects=[];this.projectiles.clear(true,true);if(this.boss)this.boss.isAttackRunning=false;}
  bossDefeated(){this.transitioning=true;this.inputLocked=true;this.cancelBossAttack();this.enemies.clear(true,true);this.crateTimers?.forEach(t=>t?.remove(false));this.bossHud.setVisible(false);this.effects.shake(250,.008);this.effects.burst(this.boss.x,this.boss.y,0xffffff,40);audioManager.stopMusic();this.tweens.add({targets:this.boss,scale:1.5,alpha:0,angle:180,duration:1800});this.time.delayedCall(2100,()=>this.scene.start('EndingScene'));}
}
