import { addBackdrop, addButton } from './BootScene.js';
import { audioManager } from '../audioManager.js';
export class MenuScene extends Phaser.Scene{
  constructor(){super('MenuScene');}
  create(){audioManager.playMusic('menu');addBackdrop(this,'PROJECT: ESCAPE.AI','NEXUS 연구소 탈출 프로토콜 · SUBJECT 042');this.add.text(760,85,'2045 // CONTROL IS PROTECTION',{fontFamily:'monospace',fontSize:'18px',color:'#ff657e'});const items=[['게임 시작',()=>this.scene.start('DifficultyScene')],['난이도 선택',()=>this.scene.start('DifficultyScene')],['최고 기록',()=>this.scene.start('RecordsScene')],['업적',()=>this.scene.start('AchievementsScene')],['설정',()=>this.scene.start('SettingsScene',{returnScene:'MenuScene'})],['조작법',()=>this.showControls()],['제작 정보',()=>this.scene.start('CreditsScene')]];items.forEach((v,i)=>addButton(this,270,190+i*62,v[0],v[1],350));this.add.text(690,205,'NEXUS는 당신의 모든 행동을 기록합니다.',{fontFamily:'monospace',fontSize:'24px',color:'#dffffa'});this.add.text(690,255,'탈출하십시오. 분석당하기 전에.',{fontFamily:'monospace',fontSize:'19px',color:'#ff667d'});this.drawCore();}
  drawCore(){const c=this.add.container(925,460);for(let i=0;i<3;i++){const r=this.add.arc(0,0,90+i*34,15*i,280+15*i,false,0x06121c).setStrokeStyle(5-i, i===1?0x26ffe6:0xff365f,.65);c.add(r);this.tweens.add({targets:r,angle:i%2?360:-360,duration:7000+i*1800,repeat:-1});}c.add([this.add.circle(0,0,72,0x170812).setStrokeStyle(6,0xff365f),this.add.circle(0,0,22,0xffffff).setStrokeStyle(8,0xff365f)]);}
  showControls(){if(this.popup)return;const shade=this.add.rectangle(640,360,1280,720,0x000000,.78).setDepth(50).setInteractive(),panel=this.add.rectangle(640,360,760,500,0x071722).setStrokeStyle(3,0x26ffe6).setDepth(51),text=this.add.text(640,330,'조작법\n\nWASD / 방향키  이동\n마우스 왼쪽 / J  3타 근접 공격\nShift  대시\nF  물체 집기 / 내려놓기\n마우스 오른쪽 / K  투척\nQ  EMP\nE  장치·문·기록 상호작용\nEsc  일시정지',{fontFamily:'monospace',fontSize:'23px',color:'#eaffff',align:'center',lineSpacing:10}).setOrigin(.5).setDepth(52),close=addButton(this,640,575,'닫기',()=>this.closeControls(),220).setDepth(53);this.popup=[shade,panel,text,close];}
  closeControls(){this.popup?.forEach(o=>o.destroy());this.popup=null;}
}
