import { addBackdrop, addButton } from './BootScene.js';
import { gameSession } from '../gameSession.js';
import { scoreManager } from '../scoreManager.js';
import { saveManager } from '../saveManager.js';
import { achievementManager, ACHIEVEMENTS } from '../achievementManager.js';
import { PROFILE_LABELS } from '../config.js';
import { audioManager } from '../audioManager.js';
const rank={D:0,C:1,B:2,A:3,S:4};
export class ResultScene extends Phaser.Scene{
  constructor(){super('ResultScene');}
  create(){audioManager.playMusic('menu');const result=this.commitResult();addBackdrop(this,'MISSION RESULT',result.newRecord?'NEW RECORD':'ESCAPE PROTOCOL COMPLETE');if(result.newRecord)audioManager.playSfx('record');const t=Math.floor(gameSession.playTime),rows=[['최종 점수',gameSession.score.toLocaleString()],['최종 등급',result.grade],['난이도',gameSession.difficulty],['클리어 시간',`${String(t/60|0).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`],['최고 콤보',gameSession.bestCombo],['받은 총 피해',Math.round(gameSession.totalDamageTaken)],['사망 횟수',gameSession.deathCount],['일반 적 처치',gameSession.enemyKills],['투척 처치',gameSession.throwKills],['연구 기록',`${gameSession.researchLogs.length} / 4`],['최종 AI 성향',PROFILE_LABELS[gameSession.finalProfile]||'균형형']];rows.forEach((r,i)=>{const col=i<6?0:1,row=i<6?i:i-6,x=190+col*520,y=180+row*58;this.add.text(x,y,r[0],{fontFamily:'monospace',fontSize:'18px',color:'#77fff0'});this.add.text(x+410,y,String(r[1]),{fontFamily:'monospace',fontSize:'20px',fontStyle:'bold',color:'#ffffff'}).setOrigin(1,0);});const unlocked=gameSession.newlyUnlocked.map(id=>ACHIEVEMENTS[id]?.name).filter(Boolean).join(', ')||'없음';this.add.text(710,500,`새 업적: ${unlocked}`,{fontFamily:'monospace',fontSize:'17px',color:'#ffdc77',wordWrap:{width:450}});addButton(this,900,620,'다시 플레이',()=>this.guard(()=>{gameSession.newGame(saveManager.data.lastDifficulty);this.scene.start('DifficultyScene');}),300);addButton(this,1220-150,680,'메인 메뉴',()=>this.guard(()=>this.scene.start('MenuScene')),260);}
  commitResult(){if(gameSession.resultCommitted)return {grade:scoreManager.grade(gameSession.score),newRecord:false};if(gameSession.deathCount===0)scoreManager.award('bonus',1200,'final-no-death',false);if(gameSession.playTime<=600)scoreManager.award('bonus',800,'final-under-ten-minutes',false);if(gameSession.researchLogs.length===4)scoreManager.award('bonus',800,'final-all-logs',false);if(gameSession.totalDamageTaken<=100)scoreManager.award('bonus',600,'final-low-damage',false);achievementManager.evaluateClear();const d=saveManager.data,grade=scoreManager.grade(gameSession.score),newRecord=gameSession.score>d.highestScore;d.highestScore=Math.max(d.highestScore,gameSession.score);if(rank[grade]>rank[d.bestGrade])d.bestGrade=grade;if(d.fastestClearTime==null||gameSession.playTime<d.fastestClearTime)d.fastestClearTime=gameSession.playTime;d.highestCombo=Math.max(d.highestCombo,gameSession.bestCombo);if(gameSession.difficulty==='Normal')d.normalCleared=true;if(gameSession.difficulty==='Hard')d.hardCleared=true;d.totalPlayCount++;d.totalEnemyKills+=gameSession.enemyKills;if(d.totalEnemyKills>=20)achievementManager.unlock('destroyer');saveManager.persist();gameSession.resultCommitted=true;return {grade,newRecord};}
  guard(fn){if(this.clicked)return;this.clicked=true;fn();}
}
