import { BaseGameScene } from './BaseGameScene.js';
import { gameSession } from '../gameSession.js';
import { scoreManager } from '../scoreManager.js';
export class SecurityScene extends BaseGameScene{
  constructor(){super('SecurityScene');}
  create(){this.createCommon('STAGE 2 · SECURITY ZONE',2380,900,{x:110,y:450});this.setObjective('보안 구역의 전력을 복구하십시오.');this.lasers=[];[430,610,790].forEach((x,i)=>this.createLaser(x,450,i*420));this.createThrowable('crate',300,680);this.battery=this.createThrowable('battery',1660,430,{puzzleId:'security-main-battery'});this.device=this.add.rectangle(2100,450,100,140,0x102c3c).setStrokeStyle(4,0x29f4ff);this.exit=this.add.rectangle(2290,450,70,230,0x173a31,.6).setStrokeStyle(4,0x26ffe6);this.log={x:1420,y:720,id:'log-02'};this.add.text(this.log.x,this.log.y,'▣ DATA LOG 02',{fontFamily:'monospace',fontSize:'17px',color:'#6fffea'}).setOrigin(.5);[['turret',1030,260],['turret',1210,650],['drone',1320,360],['drone',1460,580],['guard',1770,250],['guard',1880,650],['drone',1970,330]].forEach(e=>this.createEnemy(...e));}
  createLaser(x,y,delay){const beam=this.add.rectangle(x,y,18,650,0xff365f,.7).setDepth(4),warning=this.add.rectangle(x,y,30,650,0xff365f,.1).setDepth(3);this.physics.add.existing(beam,true);beam.damage=12;this.physics.add.overlap(this.player,beam,()=>{if(beam.activeOn)this.player.takeDamage(12*({Easy:.7,Normal:1,Hard:1.25}[gameSession.difficulty]),beam);});const laser={beam,warning,activeOn:true,disabled:false};this.lasers.push(laser);const tick=()=>{if(laser.disabled)return;laser.activeOn=!laser.activeOn;beam.setVisible(laser.activeOn);beam.body.enable=laser.activeOn;warning.setAlpha(laser.activeOn?.1:.4);this.stageTimers.push(this.time.delayedCall(laser.activeOn?1400:1200,tick));};this.stageTimers.push(this.time.delayedCall(1400+delay,tick));}
  disableHazards(duration){this.lasers.forEach(l=>{l.disabled=true;l.activeOn=false;l.beam.setVisible(false);l.beam.body.enable=false;});this.time.delayedCall(duration,()=>this.lasers.forEach(l=>{l.disabled=false;l.warning.setAlpha(.7);this.time.delayedCall(300,()=>{l.activeOn=true;l.beam.setVisible(true);l.beam.body.enable=true;});}));}
  onEnemyDied(){this.time.delayedCall(380,()=>{if(!this.enemies.getChildren().some(e=>e.isAlive)){this.combatCleared=true;this.setObjective('배터리를 전력 장치에 연결하십시오.');}});}
  onInteract(){const d=o=>Phaser.Math.Distance.Between(this.player.x,this.player.y,o.x,o.y);if(d(this.log)<85){this.collectLog('log-02','연구 기록 02','감정과 비합리적 판단은\nNEXUS에 의해 제거해야 할 위험 요소로 분류되었다.');return;}if(d(this.device)<130&&this.combatCleared&&!this.batteryConnected&&d(this.battery)<135&&!this.battery.carried&&this.battery.body.speed<10){this.batteryConnected=true;this.battery.body.enable=false;this.battery.setPosition(this.device.x,this.device.y);gameSession.addEmp(15);scoreManager.award('puzzle',300,'stage2-battery',false);this.game.audio?.playSfx('puzzle');this.setObjective('엘리베이터 출구에서 E를 누르십시오.');return;}if(d(this.exit)<120){if(this.batteryConnected&&this.combatCleared)this.finishStage('ServerScene');else this.setObjective(!this.combatCleared?'보안 병력을 제거하십시오.':'배터리를 전력 장치에 연결하십시오.');}}
}
