import { BaseGameScene } from './BaseGameScene.js';
import { gameSession } from '../gameSession.js';
import { scoreManager } from '../scoreManager.js';
export class ServerScene extends BaseGameScene{
  constructor(){super('ServerScene');}
  create(){this.createCommon('STAGE 3 · CENTRAL SERVER',2380,900,{x:110,y:450});this.profile=gameSession.temporaryProfile||'balanced';this.setObjective('중앙 서버의 방어 시스템을 무력화하십시오.');this.crackedWall=this.addWall(1260,450,55,500,0x382a2c);this.cracks=this.add.text(1260,450,'╱╲\n╲╱\n╱╲',{fontFamily:'monospace',fontSize:'43px',color:'#ff7f7f',align:'center'}).setOrigin(.5).setDepth(7);this.barrel=this.createThrowable('barrel',930,450,{puzzleId:'server-wall-barrel'});this.exit=this.add.rectangle(2280,450,75,240,0x173a31,.6).setStrokeStyle(4,0x26ffe6);this.terminal=this.add.rectangle(2100,450,90,120,0x122f40).setStrokeStyle(4,0xff365f);this.logs=[{x:1450,y:180,id:'log-03'},{x:1900,y:720,id:'log-04'}];this.logs.forEach((l,i)=>this.add.text(l.x,l.y,`▣ DATA LOG 0${i+3}`,{fontFamily:'monospace',fontSize:'17px',color:'#6fffea'}).setOrigin(.5));[['charger',480,280],['drone',560,600],['drone',740,340],['guard',1480,300],['guard',1650,620],['turret',1880,250],['charger',1840,610],['drone',2050,310]].forEach(e=>this.createEnemy(...e));}
  onBarrelExploded(barrel){if(!this.wallDestroyed&&Phaser.Math.Distance.Between(barrel.x,barrel.y,this.crackedWall.x,this.crackedWall.y)<=180){this.wallDestroyed=true;this.crackedWall.destroy();this.cracks.destroy();gameSession.addEmp(15);scoreManager.award('puzzle',300,'stage3-wall',false);this.game.audio?.playSfx('puzzle');this.setObjective('중앙 서버 병력을 제거하십시오.');}else if(!this.wallDestroyed)this.time.delayedCall(5000,()=>{if(!this.wallDestroyed&&!this.throwables.getChildren().some(o=>o.active&&o.puzzleId==='server-wall-barrel'))this.barrel=this.createThrowable('barrel',930,450,{puzzleId:'server-wall-barrel'});});}
  onEnemyDied(){this.time.delayedCall(380,()=>{if(!this.enemies.getChildren().some(e=>e.isAlive)){this.combatCleared=true;this.terminal.setStrokeStyle(4,0x26ffe6);this.setObjective('중앙 서버 단말기를 활성화하십시오.');}});}
  onInteract(){const d=o=>Phaser.Math.Distance.Between(this.player.x,this.player.y,o.x,o.y);for(const l of this.logs)if(d(l)<85){const body=l.id==='log-03'?'SUBJECT 042는 인간 실험체가 아니다.\n연구원의 기억 데이터를 이식한 인공 신체다.':'NEXUS의 판단 기준에는\n인간 연구진이 제공한 편향되고 불완전한 데이터가 포함되어 있었다.';this.collectLog(l.id,`연구 기록 ${l.id.slice(-2)}`,body);return;}if(d(this.terminal)<120&&this.wallDestroyed&&this.combatCleared&&!this.terminalActive){this.terminalActive=true;this.terminal.setFillStyle(0x26ffe6,.45);this.setObjective('보스룸 입구에서 E를 누르십시오.');return;}if(d(this.exit)<120){if(this.wallDestroyed&&this.combatCleared&&this.terminalActive)this.finishStage('BossScene');else this.setObjective(!this.wallDestroyed?'폭발통으로 금이 간 벽을 파괴하십시오.':!this.combatCleared?'중앙 서버 병력을 제거하십시오.':'중앙 서버 단말기를 활성화하십시오.');}}
}
