import { addBackdrop, addButton } from './BootScene.js';
import { saveManager } from '../saveManager.js';
import { audioManager } from '../audioManager.js';
export class SettingsScene extends Phaser.Scene{
  constructor(){super('SettingsScene');}
  init(data){this.returnScene=data.returnScene||'MenuScene';}
  create(){addBackdrop(this,'설정');this.makeSlider(300,'배경음 볼륨','bgmVolume',v=>audioManager.setBgmVolume(v));this.makeSlider(400,'효과음 볼륨','sfxVolume',v=>audioManager.setSfxVolume(v));addButton(this,450,500,`화면 흔들림: ${saveManager.data.screenShakeEnabled?'켜짐':'꺼짐'}`,()=>{saveManager.set('screenShakeEnabled',!saveManager.data.screenShakeEnabled);this.scene.restart({returnScene:this.returnScene});},400);addButton(this,850,300,'전체 화면 켜기',()=>this.scale.startFullscreen(),330);addButton(this,850,375,'조작법 보기',()=>this.showControls(),330);if(this.returnScene==='MenuScene')addButton(this,850,450,'저장 기록 초기화',()=>this.confirmReset(),330);addButton(this,180,660,'뒤로',()=>this.goBack(),220);}
  makeSlider(y,label,key,onChange){this.add.text(200,y,label,{fontFamily:'monospace',fontSize:'21px',color:'#dffffa'});const value=this.add.text(810,y,`${Math.round(saveManager.data[key]*100)}%`,{fontFamily:'monospace',fontSize:'21px',color:'#ffffff'});for(let i=0;i<=10;i++){const x=430+i*34,b=this.add.rectangle(x,y+5,26,28,i/10<=saveManager.data[key]?0x26ffe6:0x17323e).setInteractive({useHandCursor:true});b.on('pointerdown',()=>{onChange(i/10);value.setText(`${i*10}%`);this.scene.restart({returnScene:this.returnScene});});}}
  showControls(){this.add.text(850,555,'WASD 이동 · J 공격 · Shift 대시\nF 집기 · K 투척 · Q EMP · E 상호작용',{fontFamily:'monospace',fontSize:'17px',color:'#8fffea',align:'center'}).setOrigin(.5);}
  confirmReset(){if(this.confirming)return;this.confirming=true;this.add.rectangle(640,360,880,250,0x03070d,.98).setStrokeStyle(3,0xff365f).setDepth(30);this.add.text(640,315,'최고 기록, 업적, 누적 통계를 모두 초기화하시겠습니까?\n이 작업은 되돌릴 수 없습니다.',{fontFamily:'monospace',fontSize:'20px',color:'#ffffff',align:'center'}).setOrigin(.5).setDepth(31);addButton(this,500,420,'취소',()=>this.scene.restart({returnScene:this.returnScene}),220).setDepth(32);addButton(this,780,420,'초기화',()=>{saveManager.resetRecords();this.scene.restart({returnScene:this.returnScene});},220).setDepth(32);}
  goBack(){if(this.returnScene==='PauseScene'){this.scene.stop();this.scene.wake('PauseScene');}else this.scene.start('MenuScene');}
}
