import { ENEMIES, DIFFICULTIES } from '../config.js';
import { gameSession } from '../gameSession.js';
import { scoreManager } from '../scoreManager.js';
import { audioManager } from '../audioManager.js';
export class Enemy extends Phaser.GameObjects.Container{
  constructor(scene,x,y,type,modifiers={}){super(scene,x,y);this.enemyType=type;this.id=`${type}-${scene.enemySerial++}`;this.cfg=ENEMIES[type];const d=DIFFICULTIES[gameSession.difficulty];this.maxHealth=Math.round(this.cfg.health*d.health);this.health=this.maxHealth;this.moveSpeed=this.cfg.speed*d.speed;this.attackDamage=this.cfg.damage*d.damage;this.cooldown=this.cfg.cooldown*(modifiers.cooldown||1);this.modifiers=modifiers;this.state='Idle';this.isAlive=true;this.isDisabled=false;this.isAttacking=false;this.hasAwardedScore=false;this.nextAttack=scene.time.now+600;this.lastHitAt=0;this.scene.add.existing(this);this.build();this.scene.physics.add.existing(this);this.body.setCircle(23,-23,-23).setCollideWorldBounds(true);this.setDepth(10);scene.enemies.add(this);}
  build(){const colors={drone:0x32e7ff,guard:0xffbd3d,turret:0xff365f,charger:0xb75cff},c=colors[this.enemyType];this.add([this.scene.add.ellipse(0,18,52,16,0x000000,.5),this.scene.add.rectangle(0,0,42,42,0x07141f).setStrokeStyle(4,c),this.scene.add.circle(0,0,12,c,.35).setStrokeStyle(3,c),this.scene.add.circle(0,0,4,0xffffff)]);}
  canAct(){return this.isAlive&&!this.isDisabled&&!this.scene.transitioning&&this.scene.player?.isAlive;}
  facePlayer(){const a=Phaser.Math.Angle.Between(this.x,this.y,this.scene.player.x,this.scene.player.y);this.rotation=a;return a;}
  moveToward(speed=this.moveSpeed){const a=this.facePlayer();this.body.setVelocity(Math.cos(a)*speed,Math.sin(a)*speed);this.state='Move';}
  disable(duration){if(!this.isAlive)return;this.isDisabled=true;this.state='Disabled';this.body.setVelocity(0);this.setTint?.(0x5dffff);this.scene.effects.ring(this.x,this.y,40,0x26ffe6,250);this.scene.time.delayedCall(duration*(this.modifiers.empDurationMultiplier||1),()=>{if(this.isAlive){this.isDisabled=false;this.clearTint?.();this.state='Alert';this.nextAttack=this.scene.time.now+700;}});}
  takeDamage(amount,source,kind='melee',comboStep=0){if(!this.isAlive)return false;let final=amount;if(this.enemyType==='guard'&&this.shielding){const incoming=Phaser.Math.Angle.Between(this.x,this.y,source.x,source.y),diff=Math.abs(Phaser.Math.Angle.Wrap(incoming-this.rotation));if(diff<Math.PI/3)final*=.3;}this.health-=final;this.state='Hit';this.lastHitAt=this.scene.time.now;this.scene.effects.damageNumber(this.x,this.y,final,'#dffffa');this.scene.effects.flash(this);this.scene.effects.burst(this.x,this.y,0x26ffe6,5);audioManager.playSfx('hit');if(source?.body&&kind!=='throw'){const a=Phaser.Math.Angle.Between(source.x,source.y,this.x,this.y),force=comboStep===3?260:130;this.body.setVelocity(Math.cos(a)*force,Math.sin(a)*force);}if(this.health<=0)this.die(kind);else this.scene.time.delayedCall(120,()=>{if(this.canAct())this.state='Alert';});return true;}
  die(kind){if(!this.isAlive)return;this.isAlive=false;this.state='Dead';this.body.enable=false;if(!this.hasAwardedScore){this.hasAwardedScore=true;scoreManager.award('enemy',this.cfg.score,`kill-${this.id}`,true);gameSession.enemyKills++;gameSession.ai.enemyKills++;if(kind==='throw'){gameSession.throwKills++;gameSession.ai.throwKills++;}if(kind==='melee')gameSession.ai.meleeKills++;gameSession.addEmp(8);}this.scene.effects.burst(this.x,this.y,0xff365f,12);audioManager.playSfx('hit');this.scene.onEnemyDied?.(this);this.scene.tweens.add({targets:this,alpha:0,scale:.2,angle:180,duration:350,onComplete:()=>this.destroy()});}
  attackWindup(callback,duration=450){if(!this.canAct()||this.isAttacking)return;this.isAttacking=true;this.state='AttackWindup';this.body.setVelocity(0);const mark=this.scene.effects.ring(this.x,this.y,50,0xff365f,duration);audioManager.playSfx('warning');this.scene.time.delayedCall(duration,()=>{if(this.canAct()){this.state='Attack';callback();}this.isAttacking=false;this.nextAttack=this.scene.time.now+this.cooldown;mark?.destroy?.();});}
  update(){if(!this.canAct()){this.body?.setVelocity(0);return;}this.moveToward();}
  onWallHit(){this.body.setVelocity(this.body.velocity.y*.5,-this.body.velocity.x*.5);}
}
