import { DIFFICULTIES, SCORE } from '../config.js';
import { gameSession } from '../gameSession.js';
import { scoreManager } from '../scoreManager.js';
import { audioManager } from '../audioManager.js';
export class NexusBoss extends Phaser.GameObjects.Container{
  constructor(scene,x,y){super(scene,x,y);this.id='nexus-core';const d=DIFFICULTIES[gameSession.difficulty];this.maxHealth=600*d.health;this.health=this.maxHealth;this.attackDamageMultiplier=d.damage;this.state='Inactive';this.phase=1;this.isAlive=true;this.isInvulnerable=true;this.isTransitioningPhase=false;this.hasEnteredPhase2=false;this.hasEnteredPhase3=false;this.isAttackRunning=false;this.hasAwardedBossScore=false;this.isDeathSequenceRunning=false;this.lastAttack='';this.attackCount=0;this.empReadyAt=0;scene.add.existing(this);this.build();scene.physics.add.existing(this,true);this.body.setCircle(85,-85,-85);this.setDepth(7);}
  build(){this.ring1=this.scene.add.arc(0,0,116,0,300,false,0x0a1e2b,.5).setStrokeStyle(13,0xff365f);this.ring2=this.scene.add.arc(0,0,145,20,330,false,0x0a1e2b,.35).setStrokeStyle(7,0x26ffe6);this.core=this.scene.add.circle(0,0,82,0x1a0611).setStrokeStyle(8,0xff365f);this.lens=this.scene.add.circle(0,0,28,0xffffff).setStrokeStyle(9,0xff365f);this.add([this.ring2,this.ring1,this.core,this.scene.add.rectangle(-112,0,38,25,0x20303c),this.scene.add.rectangle(112,0,38,25,0x20303c),this.scene.add.rectangle(0,-112,25,38,0x20303c),this.scene.add.rectangle(0,112,25,38,0x20303c),this.lens]);}
  update(time){if(!this.isAlive)return;this.ring1.rotation+=.006;this.ring2.rotation-=.004;if(this.phase===3)this.lens.alpha=.65+Math.sin(time*.012)*.35;}
  takeDamage(amount,source,kind='melee'){if(!this.isAlive||this.isInvulnerable)return false;if(kind==='throw'&&this.scene.profile==='throw'&&this.scene.bossShieldActive){const incoming=Phaser.Math.Angle.Between(this.x,this.y,source.x,source.y),diff=Math.abs(Phaser.Math.Angle.Wrap(incoming-this.rotation));if(diff<Math.PI/3)amount*=.3;}if(this.state==='Overheated')amount*=1.2;this.health-=amount;this.scene.effects.damageNumber(this.x,this.y,amount,'#ff9db0');this.scene.effects.burst(source.x,source.y,0xff365f,6);if(this.health/this.maxHealth<=.6&&!this.hasEnteredPhase2)this.scene.transitionBossPhase(2);else if(this.health/this.maxHealth<=.3&&!this.hasEnteredPhase3&&!this.isTransitioningPhase)this.scene.transitionBossPhase(3);if(this.health<=0)this.die();return true;}
  emp(){const now=this.scene.time.now;if(!this.isAlive||now<this.empReadyAt){this.scene.effects.ring(this.x,this.y,110,0xb75cff,200);return;}this.empReadyAt=now+4000;this.scene.cancelBossAttack();this.state='Disabled';this.isAttackRunning=false;const duration=this.scene.profile==='emp'?(this.phase===3?400:550):1000;this.scene.effects.ring(this.x,this.y,145,0x26ffe6,350);this.scene.time.delayedCall(duration,()=>{if(this.isAlive&&!this.isTransitioningPhase)this.state=`Phase${this.phase}`;});}
  die(){if(!this.isAlive||this.isDeathSequenceRunning)return;this.isAlive=false;this.isDeathSequenceRunning=true;this.isInvulnerable=true;if(!this.hasAwardedBossScore){this.hasAwardedBossScore=true;scoreManager.award('boss',SCORE.boss,'boss-kill',true);}audioManager.playSfx('victory');this.scene.bossDefeated();}
}
