import { PLAYER } from '../config.js';
import { gameSession } from '../gameSession.js';
import { scoreManager } from '../scoreManager.js';
import { audioManager } from '../audioManager.js';
export class Player extends Phaser.GameObjects.Container{
  constructor(scene,x,y){super(scene,x,y);this.session=gameSession;this.state='Idle';this.lastDirection=new Phaser.Math.Vector2(1,0);this.invulnerable=false;this.nextAttack=0;this.nextDash=0;this.comboStep=0;this.comboDeadline=0;this.carried=null;this.isAlive=true;scene.add.existing(this);this.build();scene.physics.add.existing(this);this.body.setCircle(20,-20,-20).setCollideWorldBounds(true);this.setDepth(12);}
  build(){this.limbs=this.scene.add.container();const shadow=this.scene.add.ellipse(0,19,48,18,0x000000,.55),legs=[this.scene.add.rectangle(-9,14,9,25,0x20465a),this.scene.add.rectangle(9,14,9,25,0x20465a)],body=this.scene.add.rectangle(0,-3,30,39,0x162e42).setStrokeStyle(3,0x48fff0),head=this.scene.add.circle(0,-29,12,0xc7e1df).setStrokeStyle(3,0x163a4d),arms=[this.scene.add.rectangle(-22,-2,9,31,0x284b5f),this.scene.add.rectangle(22,-2,9,31,0x284b5f)],core=this.scene.add.circle(0,-5,7,0x26ffe6),weapon=this.scene.add.rectangle(30,-3,27,6,0x9ffff5);this.weapon=weapon;this.core=core;this.limbs.add([...legs,...arms,body,head,core,weapon]);this.add([shadow,this.limbs]);}
  directionToPointer(){const p=this.scene.input.activePointer.positionToCamera(this.scene.cameras.main);return new Phaser.Math.Vector2(p.x-this.x,p.y-this.y).normalize();}
  move(input){if(!this.isAlive||['Dash','Attack','Hit','Dead'].includes(this.state))return;let x=(input.right.isDown?1:0)-(input.left.isDown?1:0),y=(input.down.isDown?1:0)-(input.up.isDown?1:0);const v=new Phaser.Math.Vector2(x,y);if(v.lengthSq()){v.normalize();this.lastDirection.copy(v);const speed=this.session.stats.speed*(this.carried?.9:1);this.body.setVelocity(v.x*speed,v.y*speed);this.state=this.carried?'Carry':'Walk';this.limbs.rotation=Math.sin(this.scene.time.now*.012)*.04;}else{this.body.setVelocity(0);this.state=this.carried?'Carry':'Idle';}this.rotation=this.lastDirection.angle();if(this.carried){this.carried.setPosition(this.x+this.lastDirection.x*45,this.y+this.lastDirection.y*45);this.carried.setRotation(this.rotation);}}
  attack(direction=this.lastDirection){const now=this.scene.time.now;if(!this.isAlive||this.carried||this.state==='Dash'||now<this.nextAttack)return;this.lastDirection.copy(direction.normalize());this.session.ai.meleeUses++;this.comboStep=now<=this.comboDeadline?(this.comboStep%3)+1:1;this.comboDeadline=now+PLAYER.comboWindow;this.nextAttack=now+PLAYER.attackCooldown;this.state='Attack';this.body.setVelocity(0);this.weapon.rotation=-.8;this.scene.tweens.add({targets:this.weapon,rotation:.9,duration:150,yoyo:true});audioManager.playSfx(this.comboStep===3?'heavy':'swing');const range=PLAYER.attackRange[this.comboStep-1],hx=this.x+this.lastDirection.x*range,hy=this.y+this.lastDirection.y*range,zone=this.scene.add.zone(hx,hy,range,54);this.scene.physics.add.existing(zone);zone.body.setCircle(range/2,-range/2,-range/2);const hit=new Set();this.scene.physics.overlap(zone,this.scene.enemies,(z,e)=>{if(hit.has(e)||!e.isAlive)return;hit.add(e);const dmg=PLAYER.attackDamage[this.comboStep-1]*this.session.stats.meleeMultiplier;e.takeDamage(dmg,this,'melee',this.comboStep);this.session.ai.successfulMeleeHits++;scoreManager.hit();});if(this.scene.boss)this.scene.physics.overlap(zone,this.scene.boss,()=>{if(!hit.has(this.scene.boss)){hit.add(this.scene.boss);this.scene.boss.takeDamage(PLAYER.attackDamage[this.comboStep-1]*this.session.stats.meleeMultiplier,this,'melee');scoreManager.hit();}});this.scene.time.delayedCall(120,()=>zone.destroy());this.scene.time.delayedCall(210,()=>{if(this.isAlive&&this.state==='Attack')this.state='Idle';});this.scene.onTutorialAction?.('attack');}
  dash(){const scene=this.scene;if(!scene?.time)return;const now=scene.time.now;if(!this.isAlive||this.state==='Attack'||now<this.nextDash)return;this.session.ai.dashUses++;this.nextDash=now+this.session.stats.dashCooldown;this.state='Dash';this.invulnerable=true;this.body.setVelocity(this.lastDirection.x*PLAYER.dashSpeed,this.lastDirection.y*PLAYER.dashSpeed);this.setAlpha(.48);audioManager.playSfx('dash');scene.effects.ring(this.x,this.y,48,0x2b82ff,180);scene.time.delayedCall(PLAYER.dashDuration,()=>{if(!this.active||this.scene!==scene||!scene.sys.isActive())return;this.invulnerable=false;this.setAlpha(1);this.body.setVelocity(0);this.state=this.carried?'Carry':'Idle';});scene.onTutorialAction?.('dash');}
  toggleCarry(){if(!this.isAlive)return;if(this.carried){const p={x:this.x+this.lastDirection.x*55,y:this.y+this.lastDirection.y*55};this.carried.drop(p.x,p.y);this.carried=null;this.scene.onTutorialAction?.('drop');return;}let best=null,dist=75;this.scene.throwables.getChildren().forEach(o=>{if(!o.active||o.carried||o.hasExploded)return;const d=Phaser.Math.Distance.Between(this.x,this.y,o.x,o.y);if(d<dist){best=o;dist=d;}});if(best?.pickup(this)){this.carried=best;this.scene.onTutorialAction?.('pickup');}}
  throwObject(direction=this.lastDirection){if(!this.carried)return;const obj=this.carried;this.carried=null;obj.setPosition(this.x+direction.x*48,this.y+direction.y*48);obj.throw(direction.normalize(),this);this.session.ai.throwUses++;}
  useEmp(){if((this.session.empGauge??0)<100||!this.isAlive)return;this.session.empGauge=0;this.session.ai.empUses++;if(this.session.playTime-this.session.ai.lastEmpChargeCompletedAt<=8)this.session.ai.empUsesWithin8Seconds++;let affected=0;this.scene.effects.ring(this.x,this.y,this.session.stats.empRange,0x26ffe6,450);this.scene.enemies.getChildren().forEach(e=>{if(e.isAlive&&Phaser.Math.Distance.Between(this.x,this.y,e.x,e.y)<=this.session.stats.empRange){e.disable(this.session.stats.empDuration);affected++;}});this.scene.boss?.emp?.();this.scene.disableHazards?.(this.session.stats.empDuration);this.scene.onEmpUsed?.(affected);audioManager.playSfx('emp');}
  takeDamage(amount,source){const scene=this.scene;if(!this.isAlive||this.invulnerable||!scene?.time||scene.transitioning)return false;const actual=Math.min(this.session.health,amount);this.session.health-=actual;this.session.totalDamageTaken+=actual;this.session.ai.damageTaken+=actual;scoreManager.damagePenalty(actual);this.session.currentCombo=Math.floor(this.session.currentCombo/2);this.invulnerable=true;this.state='Hit';this.body.setVelocity((this.x-(source?.x||this.x))*3,(this.y-(source?.y||this.y))*3);scene.effects.flash(this,0xffffff);scene.effects.damageNumber(this.x,this.y,actual,'#ff6b6b');audioManager.playSfx('hurt');scene.time.delayedCall(500,()=>{if(this.active&&this.scene===scene&&scene.sys.isActive()){this.invulnerable=false;this.state=this.carried?'Carry':'Idle';}});if(this.session.health<=0)this.die();return true;}
  heal(amount){this.session.health=Math.min(this.session.maxHealth,this.session.health+amount);audioManager.playSfx('heal');}
  die(){const scene=this.scene;if(!this.isAlive||!scene?.time)return;this.isAlive=false;this.state='Dead';this.body.enable=false;if(this.carried){this.carried.drop(this.x+35,this.y);this.carried=null;}scene.tweens.add({targets:this,angle:90,alpha:.25,duration:650});scene.time.delayedCall(800,()=>{if(this.scene===scene&&scene.sys.isActive())scene.playerDied();});}
}
