import { THROWABLES } from '../config.js';
import { audioManager } from '../audioManager.js';
export class ThrowableObject extends Phaser.GameObjects.Container{
  constructor(scene,x,y,type='crate',options={}){super(scene,x,y);this.type=type;this.config=THROWABLES[type];this.puzzleId=options.puzzleId||null;this.spawnPoint={x,y};this.carried=false;this.thrown=false;this.hitTargets=new Set();this.hasExploded=false;this.scene.add.existing(this);this.build();this.scene.physics.add.existing(this);this.body.setSize(38,38).setOffset(-19,-19).setCollideWorldBounds(true).setDrag(330,330).setMaxVelocity(700);this.setDepth(8);}
  build(){const c=this.config.color;this.add([this.scene.add.rectangle(0,4,42,40,0x020812).setStrokeStyle(3,c),this.scene.add.rectangle(0,0,28,28,c,.35).setStrokeStyle(2,c),this.scene.add.circle(0,0,6,0xffffff,.9)]);if(this.type==='barrel')this.add(this.scene.add.rectangle(0,-14,28,5,0xffd45a));}
  pickup(player){if(this.carried||this.hasExploded)return false;this.carried=true;this.thrown=false;this.body.enable=false;this.setDepth(15);audioManager.playSfx('pickup');return true;}
  drop(x,y){this.carried=false;this.thrown=false;this.setPosition(x,y);this.body.enable=true;this.body.reset(x,y);this.body.setVelocity(0);this.setDepth(8);audioManager.playSfx('drop');}
  throw(dir,player){this.carried=false;this.thrown=true;this.thrower=player;this.hitTargets.clear();this.body.enable=true;this.body.reset(this.x,this.y);const speed=this.config.speed*player.session.stats.throwSpeedMultiplier;this.body.setVelocity(dir.x*speed,dir.y*speed);audioManager.playSfx('throw');}
  impact(target){if(!this.thrown||this.hitTargets.has(target)||!target?.isAlive)return;this.hitTargets.add(target);const damage=this.config.damage*this.thrower.session.stats.throwDamageMultiplier;target.takeDamage(damage,this,'throw');this.thrower.session.ai.successfulThrowHits++;this.thrower.scene.onAccurateThrow?.(this,target);if(this.type==='battery')target.disable?.(1500);if(this.type==='barrel')this.explode();else{this.thrown=false;this.body.setVelocity(this.body.velocity.x*.2,this.body.velocity.y*.2);}}
  explode(){if(this.hasExploded)return;this.hasExploded=true;this.carried=false;this.thrown=false;this.body.enable=false;this.scene.explodeBarrel?.(this);audioManager.playSfx('explosion');this.scene.time.delayedCall(120,()=>this.destroy());}
  update(){if(this.carried||!this.active)return;if(!Number.isFinite(this.x)||this.x<0||this.y<0||this.x>this.scene.physics.world.bounds.width||this.y>this.scene.physics.world.bounds.height){if(this.puzzleId)this.drop(this.spawnPoint.x,this.spawnPoint.y);else this.destroy();}if(this.thrown&&this.body.speed<35)this.thrown=false;}
}
